// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package me.vipulgupta.dice.Reponse;

public interface ECHOResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.vipulgupta.dice.Reponse.ECHORes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   *
   * @return The message.
   */
  java.lang.String getMessage();

  /**
   * <code>string message = 1;</code>
   *
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
  getMessageBytes();
}
