// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package me.vipulgupta.dice.Reponse;

public interface EXPIREATResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.vipulgupta.dice.Reponse.EXPIREATRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isChanged = 1;</code>
   * @return The isChanged.
   */
  boolean getIsChanged();
}
