// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package me.vipulgupta.dice.Reponse;

public interface EXPIRETIMEResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.vipulgupta.dice.Reponse.EXPIRETIMERes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 unixSec = 1;</code>
   * @return The unixSec.
   */
  long getUnixSec();
}
