// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package me.vipulgupta.dice.Reponse;

public interface FLUSHDBResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.vipulgupta.dice.Reponse.FLUSHDBRes)
    com.google.protobuf.MessageOrBuilder {
}
