// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package me.vipulgupta.dice.Reponse;

public interface HElementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.vipulgupta.dice.Reponse.HElement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   *
   * @return The key.
   */
  java.lang.String getKey();

  /**
   * <code>string key = 1;</code>
   *
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
  getKeyBytes();

  /**
   * <code>string value = 2;</code>
   *
   * @return The value.
   */
  java.lang.String getValue();

  /**
   * <code>string value = 2;</code>
   *
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
  getValueBytes();
}
