// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package me.vipulgupta.dice.Reponse;

/**
 * Protobuf enum {@code me.vipulgupta.dice.Reponse.Status}
 */
public enum Status
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Status_OK = 0;</code>
   */
  Status_OK(0),
  /**
   * <code>Status_ERR = 1;</code>
   */
  Status_ERR(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Status_OK = 0;</code>
   */
  public static final int Status_OK_VALUE = 0;
  /**
   * <code>Status_ERR = 1;</code>
   */
  public static final int Status_ERR_VALUE = 1;
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Status> internalValueMap =
      new com.google.protobuf.Internal.EnumLiteMap<Status>() {
        public Status findValueByNumber(int number) {
          return Status.forNumber(number);
        }
      };
  private static final Status[] VALUES = values();
  private final int value;

  private Status(int value) {
    this.value = value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Status valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Status forNumber(int value) {
    switch (value) {
      case 0:
        return Status_OK;
      case 1:
        return Status_ERR;
      default:
        return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Status>
  internalGetValueMap() {
    return internalValueMap;
  }

  public static final com.google.protobuf.Descriptors.EnumDescriptor
  getDescriptor() {
    return me.vipulgupta.dice.Reponse.ResponseProto.getDescriptor().getEnumTypes().get(0);
  }

  public static Status valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
  getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }

  public final com.google.protobuf.Descriptors.EnumDescriptor
  getDescriptorForType() {
    return getDescriptor();
  }

  // @@protoc_insertion_point(enum_scope:me.vipulgupta.dice.Reponse.Status)
}

