// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package me.vipulgupta.dice.Reponse;

public interface TYPEResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.vipulgupta.dice.Reponse.TYPERes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   *
   * @return The type.
   */
  java.lang.String getType();

  /**
   * <code>string type = 1;</code>
   *
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
  getTypeBytes();
}
