// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package me.vipulgupta.dice.Reponse;

public interface ZRANKResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.vipulgupta.dice.Reponse.ZRANKRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.me.vipulgupta.dice.Reponse.ZElement element = 2;</code>
   *
   * @return Whether the element field is set.
   */
  boolean hasElement();

  /**
   * <code>.me.vipulgupta.dice.Reponse.ZElement element = 2;</code>
   *
   * @return The element.
   */
  me.vipulgupta.dice.Reponse.ZElement getElement();

  /**
   * <code>.me.vipulgupta.dice.Reponse.ZElement element = 2;</code>
   */
  me.vipulgupta.dice.Reponse.ZElementOrBuilder getElementOrBuilder();
}
