// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package me.vipulgupta.dice.Reponse;

/**
 * Protobuf type {@code me.vipulgupta.dice.Reponse.ZRANGERes}
 */
public final class ZRANGERes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:me.vipulgupta.dice.Reponse.ZRANGERes)
    ZRANGEResOrBuilder {

  public static final int ELEMENTS_FIELD_NUMBER = 1;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:me.vipulgupta.dice.Reponse.ZRANGERes)
  private static final me.vipulgupta.dice.Reponse.ZRANGERes DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<ZRANGERes>
      PARSER = new com.google.protobuf.AbstractParser<ZRANGERes>() {
    @java.lang.Override
    public ZRANGERes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  static {
    DEFAULT_INSTANCE = new me.vipulgupta.dice.Reponse.ZRANGERes();
  }

  @SuppressWarnings("serial")
  private java.util.List<me.vipulgupta.dice.Reponse.ZElement> elements_;
  private byte memoizedIsInitialized = -1;

  // Use ZRANGERes.newBuilder() to construct.
  private ZRANGERes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ZRANGERes() {
    elements_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return me.vipulgupta.dice.Reponse.ResponseProto.internal_static_me_vipulgupta_dice_Reponse_ZRANGERes_descriptor;
  }

  public static me.vipulgupta.dice.Reponse.ZRANGERes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static me.vipulgupta.dice.Reponse.ZRANGERes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static me.vipulgupta.dice.Reponse.ZRANGERes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static me.vipulgupta.dice.Reponse.ZRANGERes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static me.vipulgupta.dice.Reponse.ZRANGERes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static me.vipulgupta.dice.Reponse.ZRANGERes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static me.vipulgupta.dice.Reponse.ZRANGERes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static me.vipulgupta.dice.Reponse.ZRANGERes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static me.vipulgupta.dice.Reponse.ZRANGERes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static me.vipulgupta.dice.Reponse.ZRANGERes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static me.vipulgupta.dice.Reponse.ZRANGERes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static me.vipulgupta.dice.Reponse.ZRANGERes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(me.vipulgupta.dice.Reponse.ZRANGERes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static me.vipulgupta.dice.Reponse.ZRANGERes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<ZRANGERes> parser() {
    return PARSER;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ZRANGERes();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return me.vipulgupta.dice.Reponse.ResponseProto.internal_static_me_vipulgupta_dice_Reponse_ZRANGERes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.vipulgupta.dice.Reponse.ZRANGERes.class,
            me.vipulgupta.dice.Reponse.ZRANGERes.Builder.class);
  }

  /**
   * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
   */
  @java.lang.Override
  public java.util.List<me.vipulgupta.dice.Reponse.ZElement> getElementsList() {
    return elements_;
  }

  /**
   * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends me.vipulgupta.dice.Reponse.ZElementOrBuilder>
  getElementsOrBuilderList() {
    return elements_;
  }

  /**
   * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
   */
  @java.lang.Override
  public int getElementsCount() {
    return elements_.size();
  }

  /**
   * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
   */
  @java.lang.Override
  public me.vipulgupta.dice.Reponse.ZElement getElements(int index) {
    return elements_.get(index);
  }

  /**
   * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
   */
  @java.lang.Override
  public me.vipulgupta.dice.Reponse.ZElementOrBuilder getElementsOrBuilder(
      int index) {
    return elements_.get(index);
  }

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) {
      return true;
    }
    if (isInitialized == 0) {
      return false;
    }

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    for (int i = 0; i < elements_.size(); i++) {
      output.writeMessage(1, elements_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) {
      return size;
    }

    size = 0;
    for (int i = 0; i < elements_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, elements_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof me.vipulgupta.dice.Reponse.ZRANGERes)) {
      return super.equals(obj);
    }
    me.vipulgupta.dice.Reponse.ZRANGERes other = (me.vipulgupta.dice.Reponse.ZRANGERes) obj;

    if (!getElementsList()
        .equals(other.getElementsList())) {
      return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) {
      return false;
    }
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getElementsCount() > 0) {
      hash = (37 * hash) + ELEMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getElementsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ZRANGERes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.vipulgupta.dice.Reponse.ZRANGERes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code me.vipulgupta.dice.Reponse.ZRANGERes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:me.vipulgupta.dice.Reponse.ZRANGERes)
      me.vipulgupta.dice.Reponse.ZRANGEResOrBuilder {

    private int bitField0_;
    private java.util.List<me.vipulgupta.dice.Reponse.ZElement> elements_ =
        java.util.Collections.emptyList();
    private com.google.protobuf.RepeatedFieldBuilderV3<
        me.vipulgupta.dice.Reponse.ZElement, me.vipulgupta.dice.Reponse.ZElement.Builder, me.vipulgupta.dice.Reponse.ZElementOrBuilder> elementsBuilder_;

    // Construct using me.vipulgupta.dice.Reponse.ZRANGERes.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return me.vipulgupta.dice.Reponse.ResponseProto.internal_static_me_vipulgupta_dice_Reponse_ZRANGERes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return me.vipulgupta.dice.Reponse.ResponseProto.internal_static_me_vipulgupta_dice_Reponse_ZRANGERes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.vipulgupta.dice.Reponse.ZRANGERes.class,
              me.vipulgupta.dice.Reponse.ZRANGERes.Builder.class);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (elementsBuilder_ == null) {
        elements_ = java.util.Collections.emptyList();
      } else {
        elements_ = null;
        elementsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return me.vipulgupta.dice.Reponse.ResponseProto.internal_static_me_vipulgupta_dice_Reponse_ZRANGERes_descriptor;
    }

    @java.lang.Override
    public me.vipulgupta.dice.Reponse.ZRANGERes getDefaultInstanceForType() {
      return me.vipulgupta.dice.Reponse.ZRANGERes.getDefaultInstance();
    }

    @java.lang.Override
    public me.vipulgupta.dice.Reponse.ZRANGERes build() {
      me.vipulgupta.dice.Reponse.ZRANGERes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.vipulgupta.dice.Reponse.ZRANGERes buildPartial() {
      me.vipulgupta.dice.Reponse.ZRANGERes result = new me.vipulgupta.dice.Reponse.ZRANGERes(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(me.vipulgupta.dice.Reponse.ZRANGERes result) {
      if (elementsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          elements_ = java.util.Collections.unmodifiableList(elements_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.elements_ = elements_;
      } else {
        result.elements_ = elementsBuilder_.build();
      }
    }

    private void buildPartial0(me.vipulgupta.dice.Reponse.ZRANGERes result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.vipulgupta.dice.Reponse.ZRANGERes) {
        return mergeFrom((me.vipulgupta.dice.Reponse.ZRANGERes) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.vipulgupta.dice.Reponse.ZRANGERes other) {
      if (other == me.vipulgupta.dice.Reponse.ZRANGERes.getDefaultInstance()) {
        return this;
      }
      if (elementsBuilder_ == null) {
        if (!other.elements_.isEmpty()) {
          if (elements_.isEmpty()) {
            elements_ = other.elements_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureElementsIsMutable();
            elements_.addAll(other.elements_);
          }
          onChanged();
        }
      } else {
        if (!other.elements_.isEmpty()) {
          if (elementsBuilder_.isEmpty()) {
            elementsBuilder_.dispose();
            elementsBuilder_ = null;
            elements_ = other.elements_;
            bitField0_ = (bitField0_ & ~0x00000001);
            elementsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                    getElementsFieldBuilder() : null;
          } else {
            elementsBuilder_.addAllMessages(other.elements_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              me.vipulgupta.dice.Reponse.ZElement m =
                  input.readMessage(
                      me.vipulgupta.dice.Reponse.ZElement.parser(),
                      extensionRegistry);
              if (elementsBuilder_ == null) {
                ensureElementsIsMutable();
                elements_.add(m);
              } else {
                elementsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private void ensureElementsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        elements_ = new java.util.ArrayList<me.vipulgupta.dice.Reponse.ZElement>(elements_);
        bitField0_ |= 0x00000001;
      }
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public java.util.List<me.vipulgupta.dice.Reponse.ZElement> getElementsList() {
      if (elementsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(elements_);
      } else {
        return elementsBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public int getElementsCount() {
      if (elementsBuilder_ == null) {
        return elements_.size();
      } else {
        return elementsBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public me.vipulgupta.dice.Reponse.ZElement getElements(int index) {
      if (elementsBuilder_ == null) {
        return elements_.get(index);
      } else {
        return elementsBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public Builder setElements(
        int index, me.vipulgupta.dice.Reponse.ZElement value) {
      if (elementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElementsIsMutable();
        elements_.set(index, value);
        onChanged();
      } else {
        elementsBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public Builder setElements(
        int index, me.vipulgupta.dice.Reponse.ZElement.Builder builderForValue) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        elements_.set(index, builderForValue.build());
        onChanged();
      } else {
        elementsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public Builder addElements(me.vipulgupta.dice.Reponse.ZElement value) {
      if (elementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElementsIsMutable();
        elements_.add(value);
        onChanged();
      } else {
        elementsBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public Builder addElements(
        int index, me.vipulgupta.dice.Reponse.ZElement value) {
      if (elementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElementsIsMutable();
        elements_.add(index, value);
        onChanged();
      } else {
        elementsBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public Builder addElements(
        me.vipulgupta.dice.Reponse.ZElement.Builder builderForValue) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        elements_.add(builderForValue.build());
        onChanged();
      } else {
        elementsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public Builder addElements(
        int index, me.vipulgupta.dice.Reponse.ZElement.Builder builderForValue) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        elements_.add(index, builderForValue.build());
        onChanged();
      } else {
        elementsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public Builder addAllElements(
        java.lang.Iterable<? extends me.vipulgupta.dice.Reponse.ZElement> values) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, elements_);
        onChanged();
      } else {
        elementsBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public Builder clearElements() {
      if (elementsBuilder_ == null) {
        elements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        elementsBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public Builder removeElements(int index) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        elements_.remove(index);
        onChanged();
      } else {
        elementsBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public me.vipulgupta.dice.Reponse.ZElement.Builder getElementsBuilder(
        int index) {
      return getElementsFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public me.vipulgupta.dice.Reponse.ZElementOrBuilder getElementsOrBuilder(
        int index) {
      if (elementsBuilder_ == null) {
        return elements_.get(index);
      } else {
        return elementsBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public java.util.List<? extends me.vipulgupta.dice.Reponse.ZElementOrBuilder>
    getElementsOrBuilderList() {
      if (elementsBuilder_ != null) {
        return elementsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(elements_);
      }
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public me.vipulgupta.dice.Reponse.ZElement.Builder addElementsBuilder() {
      return getElementsFieldBuilder().addBuilder(
          me.vipulgupta.dice.Reponse.ZElement.getDefaultInstance());
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public me.vipulgupta.dice.Reponse.ZElement.Builder addElementsBuilder(
        int index) {
      return getElementsFieldBuilder().addBuilder(
          index, me.vipulgupta.dice.Reponse.ZElement.getDefaultInstance());
    }

    /**
     * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
     */
    public java.util.List<me.vipulgupta.dice.Reponse.ZElement.Builder>
    getElementsBuilderList() {
      return getElementsFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        me.vipulgupta.dice.Reponse.ZElement, me.vipulgupta.dice.Reponse.ZElement.Builder, me.vipulgupta.dice.Reponse.ZElementOrBuilder>
    getElementsFieldBuilder() {
      if (elementsBuilder_ == null) {
        elementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            me.vipulgupta.dice.Reponse.ZElement, me.vipulgupta.dice.Reponse.ZElement.Builder, me.vipulgupta.dice.Reponse.ZElementOrBuilder>(
            elements_,
            ((bitField0_ & 0x00000001) != 0),
            getParentForChildren(),
            isClean());
        elements_ = null;
      }
      return elementsBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:me.vipulgupta.dice.Reponse.ZRANGERes)
  }

}

