// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package me.vipulgupta.dice.Reponse;

public interface ZRANGEResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.vipulgupta.dice.Reponse.ZRANGERes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
   */
  java.util.List<me.vipulgupta.dice.Reponse.ZElement> 
      getElementsList();
  /**
   * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
   */
  me.vipulgupta.dice.Reponse.ZElement getElements(int index);
  /**
   * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
   */
  int getElementsCount();
  /**
   * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
   */
  java.util.List<? extends me.vipulgupta.dice.Reponse.ZElementOrBuilder> 
      getElementsOrBuilderList();
  /**
   * <code>repeated .me.vipulgupta.dice.Reponse.ZElement elements = 1;</code>
   */
  me.vipulgupta.dice.Reponse.ZElementOrBuilder getElementsOrBuilder(
      int index);
}
