// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package com.dice.Reponse;

public interface EXISTSResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dice.Reponse.EXISTSRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 count = 1;</code>
   * @return The count.
   */
  long getCount();
}
