// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package com.dice.Reponse;

public interface HGETALLWATCHResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dice.Reponse.HGETALLWATCHRes)
    com.google.protobuf.MessageOrBuilder {
}
