// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package com.dice.Reponse;

public interface HGETALLResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dice.Reponse.HGETALLRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.dice.Reponse.HElement elements = 1;</code>
   */
  java.util.List<com.dice.Reponse.HElement> 
      getElementsList();
  /**
   * <code>repeated .com.dice.Reponse.HElement elements = 1;</code>
   */
  com.dice.Reponse.HElement getElements(int index);
  /**
   * <code>repeated .com.dice.Reponse.HElement elements = 1;</code>
   */
  int getElementsCount();
  /**
   * <code>repeated .com.dice.Reponse.HElement elements = 1;</code>
   */
  java.util.List<? extends com.dice.Reponse.HElementOrBuilder> 
      getElementsOrBuilderList();
  /**
   * <code>repeated .com.dice.Reponse.HElement elements = 1;</code>
   */
  com.dice.Reponse.HElementOrBuilder getElementsOrBuilder(
      int index);
}
