// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package com.dice.Reponse;

public interface HGETResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dice.Reponse.HGETRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   *
   * @return The value.
   */
  java.lang.String getValue();

  /**
   * <code>string value = 1;</code>
   *
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
  getValueBytes();
}
