// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package com.dice.Reponse;

public interface INCRResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dice.Reponse.INCRRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 value = 1;</code>
   *
   * @return The value.
   */
  long getValue();
}
