// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package com.dice.Reponse;

/**
 * Protobuf type {@code com.dice.Reponse.KEYSRes}
 */
public final class KEYSRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.dice.Reponse.KEYSRes)
    KEYSResOrBuilder {

  private static final long serialVersionUID = 0L;

  // Use KEYSRes.newBuilder() to construct.
  private KEYSRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private KEYSRes() {
    keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new KEYSRes();
  }

  @java.lang.Override
  public com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  public static com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.dice.Reponse.ResponseProto.internal_static_com_dice_Reponse_KEYSRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.dice.Reponse.ResponseProto.internal_static_com_dice_Reponse_KEYSRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dice.Reponse.KEYSRes.class, com.dice.Reponse.KEYSRes.Builder.class);
  }

  public static final int KEYS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList keys_;

  /**
   * <code>repeated string keys = 1;</code>
   *
   * @return A list containing the keys.
   */
  public com.google.protobuf.ProtocolStringList
  getKeysList() {
    return keys_;
  }

  /**
   * <code>repeated string keys = 1;</code>
   *
   * @return The count of keys.
   */
  public int getKeysCount() {
    return keys_.size();
  }

  /**
   * <code>repeated string keys = 1;</code>
   *
   * @param index The index of the element to return.
   * @return The keys at the given index.
   */
  public java.lang.String getKeys(int index) {
    return keys_.get(index);
  }

  /**
   * <code>repeated string keys = 1;</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the keys at the given index.
   */
  public com.google.protobuf.ByteString
  getKeysBytes(int index) {
    return keys_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) {
      return true;
    }
    if (isInitialized == 0) {
      return false;
    }

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    for (int i = 0; i < keys_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, keys_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) {
      return size;
    }

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < keys_.size(); i++) {
        dataSize += computeStringSizeNoTag(keys_.getRaw(i));
      }
      size += dataSize;
      size += getKeysList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof KEYSRes other)) {
      return super.equals(obj);
    }

    if (!getKeysList()
        .equals(other.getKeysList())) {
      return false;
    }
    return getUnknownFields().equals(other.getUnknownFields());
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getKeysCount() > 0) {
      hash = (37 * hash) + KEYS_FIELD_NUMBER;
      hash = (53 * hash) + getKeysList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dice.Reponse.KEYSRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.dice.Reponse.KEYSRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.dice.Reponse.KEYSRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.dice.Reponse.KEYSRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.dice.Reponse.KEYSRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.dice.Reponse.KEYSRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.dice.Reponse.KEYSRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.dice.Reponse.KEYSRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dice.Reponse.KEYSRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.dice.Reponse.KEYSRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dice.Reponse.KEYSRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.dice.Reponse.KEYSRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.dice.Reponse.KEYSRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code com.dice.Reponse.KEYSRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.dice.Reponse.KEYSRes)
      com.dice.Reponse.KEYSResOrBuilder {

    public static com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.dice.Reponse.ResponseProto.internal_static_com_dice_Reponse_KEYSRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.dice.Reponse.ResponseProto.internal_static_com_dice_Reponse_KEYSRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dice.Reponse.KEYSRes.class, com.dice.Reponse.KEYSRes.Builder.class);
    }

    // Construct using com.dice.Reponse.KEYSRes.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.dice.Reponse.ResponseProto.internal_static_com_dice_Reponse_KEYSRes_descriptor;
    }

    @java.lang.Override
    public com.dice.Reponse.KEYSRes getDefaultInstanceForType() {
      return com.dice.Reponse.KEYSRes.getDefaultInstance();
    }

    @java.lang.Override
    public com.dice.Reponse.KEYSRes build() {
      com.dice.Reponse.KEYSRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dice.Reponse.KEYSRes buildPartial() {
      com.dice.Reponse.KEYSRes result = new com.dice.Reponse.KEYSRes(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.dice.Reponse.KEYSRes result) {
      if (((bitField0_ & 0x00000001) != 0)) {
        keys_ = keys_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.keys_ = keys_;
    }

    private void buildPartial0(com.dice.Reponse.KEYSRes result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dice.Reponse.KEYSRes) {
        return mergeFrom((com.dice.Reponse.KEYSRes) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dice.Reponse.KEYSRes other) {
      if (other == com.dice.Reponse.KEYSRes.getDefaultInstance()) {
        return this;
      }
      if (!other.keys_.isEmpty()) {
        if (keys_.isEmpty()) {
          keys_ = other.keys_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureKeysIsMutable();
          keys_.addAll(other.keys_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureKeysIsMutable();
              keys_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.LazyStringList keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;

    private void ensureKeysIsMutable() {
      if ((bitField0_ & 0x00000001) == 0) {
        keys_ = new com.google.protobuf.LazyStringArrayList(keys_);
        bitField0_ |= 0x00000001;
      }
    }

    /**
     * <code>repeated string keys = 1;</code>
     *
     * @return A list containing the keys.
     */
    public com.google.protobuf.ProtocolStringList
    getKeysList() {
      return keys_.getUnmodifiableView();
    }

    /**
     * <code>repeated string keys = 1;</code>
     *
     * @return The count of keys.
     */
    public int getKeysCount() {
      return keys_.size();
    }

    /**
     * <code>repeated string keys = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The keys at the given index.
     */
    public java.lang.String getKeys(int index) {
      return keys_.get(index);
    }

    /**
     * <code>repeated string keys = 1;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the keys at the given index.
     */
    public com.google.protobuf.ByteString
    getKeysBytes(int index) {
      return keys_.getByteString(index);
    }

    /**
     * <code>repeated string keys = 1;</code>
     *
     * @param index The index to set the value at.
     * @param value The keys to set.
     * @return This builder for chaining.
     */
    public Builder setKeys(
        int index, java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureKeysIsMutable();
      keys_.set(index, value);
      onChanged();
      return this;
    }

    /**
     * <code>repeated string keys = 1;</code>
     *
     * @param value The keys to add.
     * @return This builder for chaining.
     */
    public Builder addKeys(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureKeysIsMutable();
      keys_.add(value);
      onChanged();
      return this;
    }

    /**
     * <code>repeated string keys = 1;</code>
     *
     * @param values The keys to add.
     * @return This builder for chaining.
     */
    public Builder addAllKeys(
        java.lang.Iterable<java.lang.String> values) {
      ensureKeysIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, keys_);
      onChanged();
      return this;
    }

    /**
     * <code>repeated string keys = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearKeys() {
      keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    /**
     * <code>repeated string keys = 1;</code>
     *
     * @param value The bytes of the keys to add.
     * @return This builder for chaining.
     */
    public Builder addKeysBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      ensureKeysIsMutable();
      keys_.add(value);
      onChanged();
      return this;
    }

    @java.lang.Override
    public Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:com.dice.Reponse.KEYSRes)
  }

  // @@protoc_insertion_point(class_scope:com.dice.Reponse.KEYSRes)
  private static final com.dice.Reponse.KEYSRes DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.dice.Reponse.KEYSRes();
  }

  public static com.dice.Reponse.KEYSRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KEYSRes>
      PARSER = new com.google.protobuf.AbstractParser<KEYSRes>() {
    @java.lang.Override
    public KEYSRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<KEYSRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KEYSRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dice.Reponse.KEYSRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

