// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package com.dice.Reponse;

public interface TTLResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dice.Reponse.TTLRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 seconds = 1;</code>
   *
   * @return The seconds.
   */
  long getSeconds();
}
