// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package com.dice.Reponse;

public interface ZCOUNTWATCHResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dice.Reponse.ZCOUNTWATCHRes)
    com.google.protobuf.MessageOrBuilder {

}
