// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/response.proto

package com.dice.Reponse;

public interface ZElementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dice.Reponse.ZElement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 score = 1;</code>
   *
   * @return The score.
   */
  long getScore();

  /**
   * <code>string member = 2;</code>
   *
   * @return The member.
   */
  java.lang.String getMember();

  /**
   * <code>string member = 2;</code>
   *
   * @return The bytes for member.
   */
  com.google.protobuf.ByteString
  getMemberBytes();

  /**
   * <code>int64 rank = 3;</code>
   *
   * @return The rank.
   */
  long getRank();
}
